# -*- coding: utf-8 -*-
"""AppAstro

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1pyvKmVGMTElSlb3eaxD-9j7DISurV1Qa
"""

import streamlit as st
import swisseph as swe
from datetime import datetime, time as dt_time
from timezonefinder import TimezoneFinder
import pytz
import time
import google.generativeai as genai
from PIL import Image
import os
import random

# --- PAGE CONFIGURATION ---
st.set_page_config(
    page_title="Yugma",
    page_icon="🧡",
    layout="centered",
    initial_sidebar_state="expanded"
)

# --- SESSION STATE SETUP ---
if 'user_profile' not in st.session_state: st.session_state.user_profile = None
if 'page' not in st.session_state: st.session_state.page = "Onboarding"
if 'dummy_profiles' not in st.session_state: st.session_state.dummy_profiles = []
if 'generated_bio' not in st.session_state: st.session_state.generated_bio = ""
# Initialize image storage variables explicitly
if 'b_img' not in st.session_state: st.session_state.b_img = None
if 'g_img' not in st.session_state: st.session_state.g_img = None

# --- CSS STYLING ---
st.markdown("""
    <style>
    .stApp { background-color: #fffaf0; }
    .profile-card { background-color: white; border-radius: 15px; padding: 15px; margin-bottom: 20px; box-shadow: 0 4px 10px rgba(0,0,0,0.05); border: 1px solid #ffeaa7; }
    .scorecard { background-color: #fafafa; border: 2px dashed #e15f41; padding: 20px; border-radius: 10px; font-family: 'Courier New', monospace; }
    .metric-badge { background: #ffeaa7; padding: 5px 10px; border-radius: 10px; font-size: 12px; font-weight: bold; color: #d35400; display: inline-block; margin: 2px; }
    h1, h2, h3 { color: #e15f41; font-family: 'Helvetica Neue', sans-serif; }
    .catchy-text { font-size: 14px; color: #636e72; font-style: italic; }
    /* Inputs */
    .stTextInput input, .stTextArea textarea { border-radius: 10px; }
    </style>
    """, unsafe_allow_html=True)

# --- UTILS & ENGINES ---
@st.cache_data
def get_coords(city_name):
    # Fallback to standard coords to prevent geocoding errors during demo
    return (19.0760, 72.8777)

class VedicMatchEngine:
    def __init__(self):
        swe.set_ephe_path('')
        self.nak_to_nadi = [0,1,2,2,1,0,0,1,2, 0,1,2,2,1,0,0,1,2, 0,1,2,2,1,0,0,1,2]
        self.rashi_lords = [2, 5, 3, 1, 0, 3, 5, 2, 4, 6, 6, 4]
        self.maitri_matrix = [[5]*7 for _ in range(7)]

    def get_planet_data(self, dt_obj, lat, lon):
        tf = TimezoneFinder()
        timezone_str = tf.timezone_at(lng=lon, lat=lat) or 'UTC'
        local_tz = pytz.timezone(timezone_str)
        local_dt = local_tz.localize(dt_obj)
        utc_dt = local_dt.astimezone(pytz.utc)

        time_dec = utc_dt.hour + (utc_dt.minute / 60.0) + (utc_dt.second / 3600.0)
        jd = swe.julday(utc_dt.year, utc_dt.month, utc_dt.day, time_dec)
        swe.set_sid_mode(swe.SIDM_LAHIRI, 0, 0)

        moon = swe.calc_ut(jd, swe.MOON, swe.FLG_SIDEREAL)[0][0]
        mars = swe.calc_ut(jd, swe.MARS, swe.FLG_SIDEREAL)[0][0]
        cusps, _ = swe.houses(jd, lat, lon, b'P')
        asc_deg = cusps[0]

        def get_house(p_deg, asc): return (int(p_deg/30) - int(asc/30) + 12) % 12 + 1

        return {
            "nakshatra": int(moon / 13.333333),
            "rashi": int(moon / 30),
            "mars_house": get_house(mars, asc_deg)
        }

    def calculate_match(self, b, g):
        score = 18
        if self.nak_to_nadi[b['nakshatra']] != self.nak_to_nadi[g['nakshatra']]: score += 8
        if b['rashi'] == g['rashi']: score += 5

        b_mang = b['mars_house'] in [1, 2, 4, 7, 8, 12]
        g_mang = g['mars_house'] in [1, 2, 4, 7, 8, 12]
        flag = "Clean" if (b_mang == g_mang) else "Manglik Clash"
        return min(36, score), flag, 0, 0

# --- AI HELPERS (FIXED MODEL NAME) ---
def rewrite_bio_with_ai(api_key, bio, dob, time_birth, place):
    if not api_key: return "⚠️ Please enter API Key in sidebar first."
    try:
        genai.configure(api_key=api_key)
        # CHANGED TO 'gemini-pro' (Standard)
        model = genai.GenerativeModel('gemini-pro')
        prompt = f"""
        Rewrite this bio: "{bio}" based on the vibe of someone born on {dob} at {time_birth} in {place}.
        Use astrology personality traits (like fiery, grounded) but DO NOT use astrology words.
        Make it sound like a cool Gen Z bio. Max 3 sentences.
        """
        return model.generate_content(prompt).text
    except Exception as e:
        return f"AI Error: {str(e)}"

def generate_viral_scorecard(api_key, b_name, g_name, score, flag):
    if not api_key: return "⚠️ Enter API Key for AI Analysis."
    try:
        genai.configure(api_key=api_key)
        # CHANGED TO 'gemini-pro' (Standard)
        model = genai.GenerativeModel('gemini-pro')
        prompt = f"""
        Create a 'Viral Relationship Scorecard' for {b_name} & {g_name}.
        Score: {score}/36. Status: {flag}.
        Format with emojis:
        🔥 **The Vibe:** [Punchy description]
        ✅ **Green Flag:** [Strength]
        🚩 **Red Flag:** [Roast]
        ☕ **The Tea:** [Prediction]
        """
        return model.generate_content(prompt).text
    except Exception as e:
        return f"AI Error: {str(e)}"

def create_dummy_profiles(gender, count=10):
    profiles = []
    names = ["Arjun", "Kabir", "Rohan"] if gender == "Female" else ["Ananya", "Diya", "Mira"]
    img_url = "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d" if gender == "Female" else "https://images.unsplash.com/photo-1544005313-94ddf0286df2"
    for i in range(count):
        profiles.append({
            "id": i, "name": names[i % 3], "age": 25 + i, "city": "Mumbai", "img": img_url,
            "dob": datetime(1995, 1, 1), "time": dt_time(12, 0)
        })
    return profiles

# --- SIDEBAR MENU ---
with st.sidebar:
    # Check for various logo formats
    if os.path.exists("yugma_logo.jpg"): st.image("yugma_logo.jpg", width=150)
    elif os.path.exists("yugma_logo.png"): st.image("yugma_logo.png", width=150)
    else: st.title("Yugma 🧡")

    api_key = st.text_input("Gemini API Key", type="password")
    st.markdown("---")

    if st.session_state.user_profile:
        st.write(f"Logged in as: **{st.session_state.user_profile['name']}**")
        if st.button("🏠 Modes"): st.session_state.page = "Modes"; st.rerun()
        if st.button("👤 My Profile"): st.session_state.page = "My Profile"; st.rerun()
        if st.button("⚙️ Engine"): st.session_state.page = "Engine"; st.rerun()
        if st.button("Logout"): st.session_state.clear(); st.rerun()

# ====================================================
# VIEW 1: ONBOARDING
# ====================================================
if not st.session_state.user_profile:
    st.title("Welcome to Yugma")
    st.markdown("<p class='catchy-text'>Your cosmic destiny awaits. Let's set up your profile.</p>", unsafe_allow_html=True)

    with st.container(border=True):
        st.markdown("### 1. The Basics")
        c1, c2 = st.columns(2)
        name = c1.text_input("Your Name")
        gender = c2.selectbox("Gender", ["Male", "Female"])

        c3, c4 = st.columns(2)
        # CHANGED: Added min_value to allow dates from 1940
        dob = c3.date_input("Date of Birth", datetime(1995, 1, 1), min_value=datetime(1940, 1, 1))
        tob = c4.time_input("Time of Birth", dt_time(12, 0))
        pob = st.text_input("Place of Birth (City)")

        st.markdown("---")
        st.markdown("### 2. Photos & Identity")
        c5, c6 = st.columns(2)
        # UNIQUE KEYS PREVENT CRASHES
        profile_pic = c5.file_uploader("Profile Photo", type=['jpg', 'png'], key="onboard_p_pic")
        palm_pic = c6.file_uploader("Your Palm (Right Hand)", type=['jpg', 'png'], key="onboard_palm_pic")

        st.markdown("---")
        st.markdown("### 3. Your Vibe (Bio)")

        bio_input = st.text_area("Draft your bio", value=st.session_state.generated_bio, placeholder="I love coffee...")

        if st.button("✨ Rewrite with AI (Based on Stars)"):
            with st.spinner("Consulting the stars..."):
                rewritten = rewrite_bio_with_ai(api_key, bio_input, dob, tob, pob)
                st.session_state.generated_bio = rewritten
                st.rerun()

        st.markdown("---")

        if st.button("Start Journey 🚀", type="primary", use_container_width=True):
            if name and pob:
                st.session_state.user_profile = {
                    "name": name, "gender": gender, "dob": dob, "tob": tob,
                    "pob": pob, "about": bio_input, "photo": profile_pic, "palm": palm_pic
                }
                st.session_state.dummy_profiles = create_dummy_profiles(gender)
                st.session_state.page = "Modes"
                st.rerun()
            else:
                st.error("Please enter Name and City")

# ====================================================
# VIEW 2: MODE SELECTION
# ====================================================
elif st.session_state.page == "Modes":
    st.title("Choose Your Path")
    c1, c2, c3 = st.columns(3)

    with c1:
        st.info("⚡ Fast")
        st.subheader("Swipeee")
        if st.button("Play Swipeee"): st.session_state.page = "Swipeee"; st.rerun()

    with c2:
        st.success("🔮 Recommended")
        st.subheader("Yugma")
        if st.button("Enter Yugma"): st.session_state.page = "Yugma"; st.rerun()

    with c3:
        st.warning("💍 Serious")
        st.subheader("Yugma +")
        if st.button("Unlock Plus"): st.session_state.page = "YugmaPlus"; st.rerun()

# ====================================================
# VIEW 3: SWIPEEE (Mindless)
# ====================================================
elif st.session_state.page == "Swipeee":
    st.subheader("Swipeee Mode")
    if st.button("← Back"): st.session_state.page = "Modes"; st.rerun()

    profiles = st.session_state.dummy_profiles[:10]
    for p in profiles:
        with st.container(border=True):
            st.image(p['img'], use_column_width=True)
            st.markdown(f"### {p['name']}, {p['age']}")
            c1, c2 = st.columns(2)
            c1.button("❌", key=f"s_no_{p['id']}", use_container_width=True)
            c2.button("💚", key=f"s_yes_{p['id']}", use_container_width=True)

# ====================================================
# VIEW 4: YUGMA (Astro Core)
# ====================================================
elif st.session_state.page == "Yugma":
    st.subheader("Yugma Mode")
    if st.button("← Back"): st.session_state.page = "Modes"; st.rerun()

    user = st.session_state.user_profile
    engine = VedicMatchEngine()

    u_data = engine.get_planet_data(datetime.combine(user['dob'], user['tob']), 19.07, 72.87)
    profiles = st.session_state.dummy_profiles[:5]

    for p in profiles:
        with st.container(border=True):
            c1, c2 = st.columns([1, 2])
            with c1: st.image(p['img'], use_column_width=True)
            with c2:
                st.markdown(f"### {p['name']}, {p['age']}")
                p_data = engine.get_planet_data(datetime.combine(p['dob'], p['time']), 19.07, 72.87)
                score, flag, _, maitri = engine.calculate_match(u_data, p_data)

                st.markdown(f"""
                <span class='metric-badge'>Vibe: {int(maitri)}/5</span>
                <span class='metric-badge'>Red Flags: {flag}</span>
                """, unsafe_allow_html=True)
                st.markdown(f"**Score:** {score}/36")

                if st.button(f"✨ Analyze", key=f"y_btn_{p['id']}", type="primary"):
                    with st.spinner("Consulting the cosmos..."):
                        scorecard = generate_viral_scorecard(api_key, user['name'], p['name'], score, flag)
                        st.markdown(f"<div class='scorecard'>{scorecard}</div>", unsafe_allow_html=True)

# ====================================================
# VIEW 5: YUGMA +
# ====================================================
elif st.session_state.page == "YugmaPlus":
    st.subheader("Yugma +")
    if st.button("← Back"): st.session_state.page = "Modes"; st.rerun()
    st.warning("💎 Premium Feature: Detailed Marriage & Lineage Report.")
    st.button("Subscribe Now")

# ====================================================
# VIEW 6: MY PROFILE
# ====================================================
elif st.session_state.page == "My Profile":
    st.title("My Profile")
    p = st.session_state.user_profile
    if p['photo']: st.image(p['photo'], width=150)
    st.write(f"**Name:** {p['name']}")
    st.write(f"**Bio:** {p['about']}")

# ====================================================
# VIEW 7: ENGINE (Manual)
# ====================================================
elif st.session_state.page == "Engine":
    st.title("Yugma Engine")
    me = st.session_state.user_profile
    with st.expander("Partner Data", expanded=True):
        t_name = st.text_input("Name")
        c1, c2 = st.columns(2)
        # CHANGED: Added min_value to allow dates from 1940
        t_dob = c1.date_input("DOB", datetime(1995, 1, 1), min_value=datetime(1940, 1, 1))
        t_time = c2.time_input("Time")

    if st.button("Generate Viral Scorecard"):
        engine = VedicMatchEngine()
        u_d = engine.get_planet_data(datetime.combine(me['dob'], me['tob']), 19.07, 72.87)
        t_d = engine.get_planet_data(datetime.combine(t_dob, t_time), 19.07, 72.87)
        score, flag, _, _ = engine.calculate_match(u_d, t_d)

        if api_key:
            st.markdown(f"<div class='scorecard'>{generate_viral_scorecard(api_key, me['name'], t_name, score, flag)}</div>", unsafe_allow_html=True)
        else:
            st.warning("Enter API Key")